name: "ChatRJr's Desk"
tagline: "Words, technology, and occasional breaks from reality."
author: "Chatman Richmond Jr."
markdown: redcarpet
redcarpet:
  extensions: ['smart']
pygments: false
exclude: ['.*', 'node_modules', '*.json', 'README.md', 'gulpfile.js', 'css/scss']
paginate: 10
permalink: /:year/:month/:title/
production_url: http://www.chatrjr.name
excerpt_separator: ""