name: "ChatRJr's Desk"
tagline: "Words, technology, and tinkering."
author: "Chatman Richmond Jr."
gems:
    - jekyll-redirect-from
markdown: rdiscount
rdiscount:
    extensions:
        - smart
        - filter_html
highlighter: null
exclude: ['.*', 'node_modules', '*.json', 'README.md', 'gulpfile.js', 'css/scss', 'version-images']
paginate: 5
permalink: /:categories/:title/
production_url: http://chatrjr.name
excerpt_separator: "d596aa409dbcf4bf9d9d57252304a921bd02e3fc"
