menu:
  Web: /categories/web
  Personal: /categories/personal
  Archives: /archives
  About: /about

social:
  networks:
    codepen: "http://codepen.io/chatrjr"
    jsfiddle: "http://jsfiddle.net/user/chatrjr/fiddles/"
    github: "http://github.com/chatrjr"
    twitter: "http://twitter.com/chatrjr"

meta:
  Style Guide: "/pattern-library"
  Email: "mailto:chatmanrjr@gmail.com"
  Source: "https://github.com/chatrjr/chatrjr.github.io/tree/hexo-source"
  RSS/Atom Feed: "http://feeds.feedburner.com/chatrjr"